USE [JINI_EDU]
GO

/****** Object:  Table [dbo].[TB_JHBAE_BOARD]    Script Date: 2023-07-12 ¿ÀÀü 9:00:35 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TB_JHBAE_BOARD](
	[NO] [int] NOT NULL,
	[TITLE] [nvarchar](100) NULL,
	[CONTENT] [nvarchar](2000) NULL,
	[REG_ID] [varchar](32) NULL,
	[REG_DT] [datetime] NULL,
	[UPD_ID] [varchar](32) NULL,
	[UPD_DT] [datetime] NULL,
	[USE_YN] [char](1) NULL,
 CONSTRAINT [PK_JHBAE_BOARD] PRIMARY KEY CLUSTERED 
(
	[NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


